_target_: equinox.nn.Sequential
layers:
  - _target_: equinox.nn.Conv2d
    in_channels: ${prod:${....state_size},3}
    out_channels: ${prod:${....state_size},2}
    kernel_size: 1
    key: ${prng_key:}
  - _target_: equinox.nn.Lambda
    fn: ${get_fn:jax.nn.relu}
  - _target_: equinox.nn.Conv2d
    in_channels: ${prod:${....state_size},2}
    out_channels: ${prod:${....state_size},2}
    kernel_size: 1
    key: ${prng_key:}
  - _target_: src.nn.activation.GatedActivation
    n_inputs: ${....state_size}
