input_output_correlations:
  _target_: src.analysis.dna.dna_to_output_dissimilarity
  _partial_: True
  save_dir: "${run_path}/analysis/${checkpoint_file}/dna2lvl_dissimilarity/"
  iterations_to_plot: null
