#@package _global_
defaults:
  - /analysis/logs/dna_guided_dev_metrics@analysis
  - /analysis/plots/generated_levels@analysis
  - /analysis/plots/mpe_repertoire@analysis
  - /analysis/plots/level_dev_steps_with_attn@analysis
  - /analysis/plots/dna_compositionality@analysis

tags: ["dnaqd", "simple_level_gen", "nca_dna", "evo"]

overrides:
  model:
    dev:
      output_dev_steps: True
