#@package _global_
defaults:
  - /analysis/logs/dna_guided_dev_metrics@analysis
  - /analysis/plots/mpe_repertoire@analysis
  # TODO: level_gen is obviously wrong, change to netgen. dna_attn_{seq,max} expect DNA grids
  # - /analysis/plots/level_gen@analysis
  # - /analysis/plots/dna_attn_seq@analysis
  # - /analysis/plots/dna_attn_max@analysis
  # - /analysis/plots/input_output_dissimilarity@analysis
  # - /analysis/plots/dna_distribution_comparison@analysis
  # - /analysis/plots/dna_measure_projection@analysis
  # - /analysis/plots/sparse_dna_to_metric_regression@analysis
  # - /analysis/plots/dna_to_metric_cross_decomposition@analysis
  # - /analysis/plots/dna_path_length_intervention@analysis

tags: ["dnaqd", "diversity_only_netgen", "ndp_dna", "evo"]

overrides:
  model:
    dev:
      output_dev_steps: True
