# @package _global_

defaults:
  - _self_  # override defaults
  - paths: default
  - analysis: ???
  - hydra: default


task_name: analyze

tags: ["dev"]

analysis: {}

seed: null

run_path: ???

checkpoint_file: null  # look for best or latest model

overrides: {}

disable_jit: False

hydra:
  run:
    dir: ${run_path}/analysis
  # output_subdir: null
