_target_: src.evo.qd.CMAOptEmitter

batch_size: 100
genotype_dim: ???
sigma_g: 1.0
min_count: 0
max_count: null  # this will set the value to np.inf
num_centroids: ${task.n_centroids}
random_key: ${prng_key:}
